name: moab-rl
dependencies:
  - pip=23.2.1
  - python=3.10.11
  - pip:
      - dm_tree==0.1.8
      - fsspec==2023.10.0
      - gymnasium==0.26.3
      - matplotlib==3.8.0
      - numpy==1.24.3
      - onnx==1.14.1
      - onnxruntime==1.16.1
      - pandas==2.0.3
      - pyarrow==13.0.0
      - pyrr==0.10.3
      - ray==2.5.1
      - scikit-image==0.22.0
      - scipy==1.11.1
      - stable-baselines3[extra]==2.1.0
      - tensorboardX==2.6.2.2
      - torch==2.0.1
